Repository TimeboardIO/timeboard, pull requests merged in 2020-02, with the labels that each got.

#423 Issues#388
  webapp/src/main/java/timeboard/webapp/JSLogger.java
  webapp/src/main/resources/public/js/datatable.js
  webapp/src/main/resources/public/js/logger.js
  webapp/src/main/resources/templates/layouts/general.html
Labels: enhancement

#427 Issues#340bis
  core/src/main/java/timeboard/core/api/TimesheetService.java
  core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java
  core/src/main/java/timeboard/core/model/SubmittedTimesheet.java
  projects/src/main/java/timeboard/projects/ProjectTimesheetValidationController.java
  projects/src/main/resources/static/js/project_timesheet_validation.js
  projects/src/main/resources/templates/project_timesheet_validation.html
Labels: enhancement

#443 Issues#133
  account/src/main/java/timeboard.account/AccountController.java
  account/src/main/resources/templates/account.html
  core/src/main/java/timeboard/core/api/ProjectService.java
  core/src/main/java/timeboard/core/api/sync/RemoteTask.java
  core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java
  core/src/main/java/timeboard/core/internal/async/ProjectSyncJob.java
  core/src/main/java/timeboard/core/model/Task.java
  plugins/project-github-import-plugin/src/main/java/timeboard/plugin/project/sync/github/GithubImportPlugin.java
  projects/src/main/java/timeboard/projects/ProjectTasksController.java
  projects/src/main/java/timeboard/projects/TasksRestAPI.java
  projects/src/main/resources/static/js/project_tasks.js
  projects/src/main/resources/templates/project_tasks.html
  webapp/src/main/resources/public/js/calendar.js
Labels: bug

#446 Issues#437
  core/src/main/java/timeboard/core/api/TimesheetService.java
  core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java
  projects/src/main/java/timeboard/projects/ProjectTimesheetValidationController.java
  timesheet/src/main/java/timeboard/organization/TimesheetController.java
  timesheet/src/main/resources/static/timesheet.js
  timesheet/src/main/resources/templates/timesheet.html
  webapp/src/main/java/timeboard/webapp/JSLoggerController.java
Labels: bug

#428 Issues#417
  projects/src/main/resources/static/js/project_timesheet_validation.js
  projects/src/main/resources/templates/project_timesheet_validation.html
  timesheet/src/main/java/timeboard/organization/TimesheetController.java
Labels: enhancement

#439 Issues#384
  core/src/main/java/timeboard/core/api/AccountService.java
  core/src/main/java/timeboard/core/internal/AccountServiceImpl.java
  core/src/main/java/timeboard/core/internal/organization/OrganizationServiceImpl.java
  integ-tests/src/test/java/timeboard/webapp/HomeFeatureATest.java
  integ-tests/src/test/java/timeboard/webapp/HomeFeatureBTest.java
  integ-tests/src/test/java/timeboard/webapp/OrganizationsTest.java
  integ-tests/src/test/java/timeboard/webapp/ProjectsTest.java
  projects/src/main/resources/templates/projects.html
  webapp/src/main/java/timeboard/webapp/SuccessfulLoginListener.java
Labels: enhancement

#447 Issues#341
  core/pom.xml
  core/src/main/java/timeboard/core/api/EmailService.java
  core/src/main/java/timeboard/core/api/TimesheetService.java
  core/src/main/java/timeboard/core/internal/EmailServiceImpl.java
  core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java
  core/src/main/java/timeboard/core/internal/observers/emails/EmailStructure.java
  core/src/main/java/timeboard/core/internal/observers/emails/SendSummaryEmail.java
  core/src/main/java/timeboard/core/internal/observers/emails/TemplateGenerator.java
  timesheet/pom.xml
  timesheet/src/main/java/timeboard/organization/TimesheetController.java
  timesheet/src/main/resources/static/js/timesheet_validation.js
  timesheet/src/main/resources/static/timesheet.js
  timesheet/src/main/resources/templates/timesheet.html
  timesheet/src/main/resources/templates/timesheet_validation.html
  webapp/src/main/java/timeboard/webapp/TimeboardWebMVCConfig.java
  webapp/src/main/resources/i18n/messages_en.properties
  webapp/src/main/resources/templates/mail/global.html
  webapp/src/main/resources/templates/mail/reminder.html
  webapp/src/main/resources/templates/mail/simple.html
  webapp/src/main/resources/templates/mail/summary.html
Labels: bug, enhancement

#441 Issues#339
  timesheet/src/main/resources/static/timesheet.js
  timesheet/src/main/resources/templates/timesheet.html
Labels: enhancement

#429 Issues#410
  timesheet/src/main/java/timeboard/organization/TimesheetController.java
  timesheet/src/main/resources/templates/timesheet.html
Labels: enhancement

#451 Issues#440
  timesheet/src/main/java/timeboard/organization/TimesheetController.java
  timesheet/src/main/resources/static/timesheet.js
  timesheet/src/main/resources/templates/timesheet.html
  webapp/src/main/resources/i18n/messages_en.properties
Labels: enhancement

#445 Issues#301
  home/src/main/java/timeboard/home/model/WeekWrapper.java
  organizations/src/main/resources/templates/org_layout.html
  projects/src/main/resources/templates/projects.html
  theme/semantic/src/themes/timeboard/elements/button.variables
  theme/semantic/src/themes/timeboard/globals/site.overrides
  theme/src/main/resources/META-INF/resources/webjars/semantic/components/button.css
  theme/src/main/resources/META-INF/resources/webjars/semantic/components/button.min.css
  theme/src/main/resources/META-INF/resources/webjars/semantic/components/site.css
  theme/src/main/resources/META-INF/resources/webjars/semantic/components/site.min.css
  theme/src/main/resources/META-INF/resources/webjars/semantic/semantic.css
  theme/src/main/resources/META-INF/resources/webjars/semantic/semantic.min.css
  timesheet/src/main/resources/static/timesheet.js
  timesheet/src/main/resources/templates/timesheet.html
  webapp/src/main/resources/public/js/general.js
  webapp/src/main/resources/public/js/number-input.js
  webapp/src/main/resources/templates/fragments/navigation.html
  webapp/src/main/resources/templates/layouts/general.html
  webapp/src/main/resources/templates/mail/timesheet.html
Labels: enhancement
